[package]
name = "salvo-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = "0.37.9"
serde = "1.0.152"
serde_json = "1.0.93"
tokio = "1.25.0"
